swb-ief/etl-pipeline

- pipeline/pipeline/calculate_metrics_file.py
- pipeline/pipeline/extract_history_file.py
- pipeline/pipeline/tasks/spreadsheets.py
Adds a task to push the city metrics data to a google spreadsheet.
Fixes #26 second checkmark.
> feat: city metrics spreadsheet

- .github/workflows/pipeline-schedule.yml
Signed-off-by: rscnt <rascnt@gmail.com>
> fix: luigi scheduled task should use local scheduler

- README.md
Updates to Readme about the Rt and Dt process
> Adding Rt and Dt calculation documentation

- pipeline/pipeline/calculate_metrics_file.py
- pipeline/tests/test_calculate_metrics_file.py
New PR created to additionaly produce non imputed columns for comparision
> Removal of imputation 22dec

- .github/workflows/update_dashboard.yml
- README.md
- backend.ini
- backend/config.py
- backend/repository/gsheet_repository.py
- tasks/update_gsheet_task.py
- tests/integration_tests/test_gsheet_repository.py
- tests/test_calculations.py
- tests/test_config.py
switching to config file and finalising the setup for phase 2
> Gsheet configuration

- pipeline/pipeline/config.py
- pipeline/pipeline/dashboard_pdf_scrapper.py
- pipeline/pipeline/tasks/spreadsheets.py
Changes to config file, editing the URL for the google sheet (changed to test sheet) will be reverted prior to merge
Purpose of  branch is to incorporate the ward pdf data scraping methods @Nozziel wrote for phase 2 into the phase 1 pipeline. 
One remaining feature is writing a method, similar to the date scraping method contained in _extract_wards_data_from_page(), to extract the page number of a particular PDF containing the "ward wise breakdown of positive cases" data.
> Ward process update

- backend/metrics/calculations.py
- tasks/update_dashboard_task.py
- tests/integration_tests/test_gsheet_repository.py
- tests/integration_tests/test_update_dashboard_task.py
- tests/test_calculations.py
Removed Levitt metrick
Had a failing tests but can't reproduce it
closes #103
> Fix failing integration test and drop levitt

- .github/workflows/Run_rt_calcs.yml
> changed 777 to full blown 3th party access to the regular 644

- tasks/update_dashboard_task.py
- tests/integration_tests/test_update_dashboard_task.py
> Added extra totals to dashboard sheets

- backend/data/extract_covid19_india_data.py
- backend/data/utility.py
- backend/metrics/calculations.py
- backend/repository/repository.py
- tasks/update_dashboard_task.py
- tests/integration_tests/test_update_dashboard_task.py
- tests/test_calculations.py
- tests/test_extract_covid19_india_data.py
closes #112 
closes #111 Merged pull request due to changes in the same files
> Ratios per million

- backend/metrics/calculations.py
- tasks/update_dashboard_task.py
- tests/test_calculations.py
closes #114 but also implements it for city and state (so it can be used for filtering)
> Fourteen day avg ratio

- backend/data/static_ward_data.csv
> updated with rest of the wrads and updated values source unknown 

- backend/data/extract_mumbai_wards_pdf.py
- backend/data/static_ward_data.py
- tasks/fetch_ward_data.py
- tasks/update_dashboard_task.py
- tests/integration_tests/test_fetch_ward_data.py
- tests/integration_tests/test_update_dashboard_task.py
- tests/test_extract_mumbai_wards_pdf.py
Finishing up the ward sheet
now also has the delta's and the imputed values.
Note: ward scraper does not have 'tested' or 'other' data available... so these are loaded as np.nan and 0 respectively
> Finished ward sheet

- backend/__init__.py
- backend/repository/__init__.py
- backend/repository/aws_file_repository.py
- requirements.txt
- tasks/fetch_ward_data.py
- tests/integration_tests/test_fetch_ward_data.py
- tests/integration_tests/test_gsheet_repository.py
created an untested/unintegrated aws file based repository (to replace google sheet repository)
> Aws file repository

- .github/workflows/code_quality.yml
- .github/workflows/update_dashboard.yml
- .gitignore
- backend.ini
- backend/repository/aws_file_repository.py
- tasks/fetch_ward_data.py
- tasks/update_dashboard_task.py
- tests/integration_tests/test_aws_file_repository.py
- tests/integration_tests/test_fetch_ward_data.py
- tests/integration_tests/test_update_dashboard_task.py
Integration tests for AWS and some minor fixes.
> integration AWS

- tasks/update_dashboard_task.py
closes #131 
column name will be MA.21.delta.confirmed
> added moving average for delta confirmed

- tasks/update_dashboard_task.py
updating metrics_needed_by_dashboard from UpdateDashboardTask. This list of features populates the 'Phase 2 - Districts' and  'Phase 2 - Wards' data files in S3.
> add total.recovered to update dashboard task

- backend/metrics/calculations.py
- tasks/districts/FetchMumbaiWardsTask.py
- tasks/update_dashboard_task.py
- tests/test_calculations.py
- tests_integration/test_update_dashboard_task.py
- fixed a few issues with the integration test
closes #146
> - added total.vaccinated

- R_scripts/Epistim_rt_wards_script.R
- tasks/epi_stats/calcRT_ward_task.py
- tasks/epi_stats/fetch_citystats.py
- tasks/epi_stats/fetch_wardstats.py
- tasks/updateEpiStatsRepo_task.py
- tasks/updateEpiStatsRepo_wards_task.py
Edited code to update Phase 2 - Districts.csv file and create a copy Phase 2 - DistrictsRt.csv
(Please check the code to see if I've chosen the right column from the Phase2_RT.csv file)
> Svd09 patch r proc 4

- .github/workflows/Run_rt_calcs.yml
- R_scripts/Epistim_rt_districts_script.R
- R_scripts/Epistim_rt_wards_script.R
- R_scripts/dt_script.py
- tasks/epi_stats/calcDT_ward_task.py
- tasks/epi_stats/fetch_citystats.py
- tasks/updateEpiStatsRepo_districts_task.py
- tasks/updateEpiStatsRepo_wards_task.py
Added code for ward DT/RT.
Fixed critical districts criteria.
Updated yml to run both district and ward processes
> Svd09 patch r proc 5

- backend/metrics/calculations.py
- tests/test_calculations.py
MA.21.delta positivity and MA.21.delta.tested hard stopped post 29th jan 2021 as delta.tested and delta.positivity is 0 post that date.
> Hard stop post 29th jan

- tasks/epi_stats/fetch_citystats.py
Modify criteria 1 to pick top 30 districts
Modify criteria 2 to pick top cities based on active cases (rather than cumulative)
also exclude the 30 districts picked in criteria 1 while picking the top cities in criteria 2
> Update criteria for critical_districts selection

- tasks/districts/FetchMumbaiWardsTask.py
The link has been change to https from http (the http link doesn't work anymore)
> Update link to wards dashboard

- tasks/districts/DownloadFileTask.py
Skipping certificate verification
> Skip verification

- backend/data/extract_mumbai_wards_pdf.py
Update extract_mumbai_wards_pdf.py  with more general functions for pages in the Mumbai report with only one bar graph of data that allow data to be easily extracted with just some additions to the config in pages_config. Passed testing via 'Update COVID19 Dashboard' Action.
> Cb update mumbai extract
